version: '3.8'
services: 
  postgres:
    image: "postgres"
    environment: 
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports: 
      - "5432:5432"
    volumes: 
      - ./sql/:/docker-entrypoint-initdb.d

  api:
    image: "brucedominguez/web-api-healthcheck:latest"
    restart: on-failure
    environment: 
        - POSTGRES_HOST
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_DB
    ports:
      - "8080:8080"
    depends_on: 
      - "postgres"